// ============================================================
// R2 分析引擎层 — Mock 数据（用于开发和测试）
// 以 facebook/react 为参考，覆盖全部 13 个检测项
// ============================================================

import type { GithubData, AnalysisResult } from '@/types';
import { analyze } from './analyze';

/**
 * Mock GitHub 仓库数据
 *
 * 模拟一个"社区标准满分"的开源项目：
 * - 7 个文件检测项全部通过
 * - README 覆盖全部 6 个内容维度
 */
export const mockGithubData: GithubData = {
  repoInfo: {
    owner: 'facebook',
    repo: 'react',
    fullName: 'facebook/react',
    description:
      'The library for web and native user interfaces. A declarative, efficient, and flexible JavaScript library for building user interfaces.',
    language: 'JavaScript',
    stars: 232000,
    forks: 47600,
    createdAt: '2013-05-24T00:00:00Z',
    updatedAt: '2026-07-01T12:00:00Z',
    defaultBranch: 'main',
    license: 'MIT',
  },

  fileList: [
    // 5 个评分文件
    { name: 'README.md', path: 'README.md', type: 'file' },
    { name: 'LICENSE', path: 'LICENSE', type: 'file' },
    { name: '.gitignore', path: '.gitignore', type: 'file' },
    { name: 'CONTRIBUTING.md', path: 'CONTRIBUTING.md', type: 'file' },
    { name: 'CHANGELOG.md', path: 'CHANGELOG.md', type: 'file' },
    // 2 个补充文件
    { name: 'package.json', path: 'package.json', type: 'file' },
    { name: 'ci.yml', path: '.github/workflows/ci.yml', type: 'file' },
    { name: 'release.yml', path: '.github/workflows/release.yml', type: 'file' },
    // 目录
    { name: '.editorconfig', path: '.editorconfig', type: 'file' },
    { name: 'compiler', path: 'compiler', type: 'dir' },
    { name: 'fixtures', path: 'fixtures', type: 'dir' },
    { name: 'packages', path: 'packages', type: 'dir' },
    { name: 'scripts', path: 'scripts', type: 'dir' },
    { name: 'src', path: 'src', type: 'dir' },
  ],

  readmeContent: [
    '# React',
    '',
    '![React banner](https://example.com/react-banner.png)',
    '',
    'React is a JavaScript library for building user interfaces.',
    'It lets you compose complex UIs from small, isolated pieces of code called "components".',
    'React can render on the server using Node.js, on the web, and on mobile devices using React Native.',
    '',
    '## Features',
    '',
    '- **Declarative**: React makes it painless to create interactive UIs.',
    '- **Component-Based**: Build encapsulated components that manage their own state.',
    '- **Learn Once, Write Anywhere**: Develop new features without rewriting existing code.',
    '',
    '## Getting Started',
    '',
    '### Prerequisites',
    '- Node.js (>= 18)',
    '- npm or yarn',
    '',
    '### Installation',
    '',
    '```bash',
    'git clone https://github.com/facebook/react.git',
    'cd react',
    'npm install',
    'npm run build',
    'npm test',
    'npm start',
    '```',
    '',
    '## API Reference',
    '',
    '### React.createElement',
    '',
    '```js',
    'React.createElement(type, [props], [...children])',
    '```',
    '',
    'Creates and returns a new React element.',
    '',
    '### React.useState',
    '',
    '```js',
    'const [state, setState] = useState(initialState);',
    '```',
    '',
    'Returns a stateful value and a function to update it.',
    '',
    '## Tech Stack / Built With',
    '',
    '- **JavaScript** — Core language',
    '- **TypeScript** — Type definitions',
    '- **React** — The library itself :)',
    '- **Rollup** — Module bundler',
    '- **Jest** — Testing framework',
    '- **ESLint** — Code linting',
    '- **Prettier** — Code formatting',
    '',
    '## Project Structure',
    '',
    '```',
    'react/',
    '├── compiler/       # React Compiler (React Forget)',
    '├── fixtures/       # Test fixtures',
    '├── packages/       # React packages (react, react-dom, etc.)',
    '│   ├── react/',
    '│   ├── react-dom/',
    '│   └── react-reconciler/',
    '├── scripts/        # Build and CI scripts',
    '│   ├── jest/',
    '│   ├── rollup/',
    '│   └── release/',
    '└── src/            # Source code',
    '```',
    '',
    '## Contributing',
    '',
    'Please read [CONTRIBUTING.md](./CONTRIBUTING.md) for details on our code of conduct',
    'and the process for submitting pull requests.',
    '',
    '## Deployment / Release',
    '',
    'React releases are published to npm. Build the production bundle with:',
    '',
    '```bash',
    'npm run build',
    'npm publish',
    '```',
    '',
    'See the [release workflow](./scripts/release/README.md) for the full CI/CD pipeline details.',
    '',
    '## Screenshots',
    '',
    '![React DevTools](https://react.dev/images/home/dom_manipulation.png)',
    '',
    '## License',
    '',
    'React is [MIT licensed](./LICENSE).',
  ].join('\n'),
};

/** Mock 分析结果 —— 由 analyze(mockGithubData) 实时计算 */
export const mockAnalysisResult: AnalysisResult = analyze(mockGithubData);
